spring:
  application:
    name: gateway-service
  
  profiles:
    active: local
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Task Service Routes
        - id: task-service-routes
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: task-service-circuit-breaker
                fallbackUri: forward:/fallback/task-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
            - StripPrefix=0
          metadata:
            response-timeout: 5000
            connect-timeout: 3000
        
        # NLP Engine Routes
        - id: nlp-engine-routes
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/nlp/**
          filters:
            - name: CircuitBreaker
              args:
                name: nlp-engine-circuit-breaker
                fallbackUri: forward:/fallback/nlp-engine
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST
            - StripPrefix=1
          metadata:
            response-timeout: 10000
            connect-timeout: 5000
        
        # Speech Service Routes
        - id: speech-service-routes
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/speech/**
          filters:
            - name: CircuitBreaker
              args:
                name: speech-service-circuit-breaker
                fallbackUri: forward:/fallback/speech-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST
            - StripPrefix=1
          metadata:
            response-timeout: 30000
            connect-timeout: 5000
        
        # Health Check Routes
        - id: health-check-routes
          uri: http://localhost:8081
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: health-check-circuit-breaker
                fallbackUri: forward:/fallback/health

  # Redis Configuration for Rate Limiting
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Server Configuration
server:
  port: ${GATEWAY_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      task-service-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      nlp-engine-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      speech-service-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      health-check-circuit-breaker:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 3s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 5

# Logging Configuration
logging:
  level:
    com.smartjarvis.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    io.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway.log

# Gateway specific configuration
gateway:
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  security:
    enabled: false  # Set to true in production
    jwt:
      secret: ${JWT_SECRET:your-secret-key}
      expiration: 86400000  # 24 hours
  rate-limiting:
    enabled: true
    default-rate: 10
    default-burst: 20
  monitoring:
    enabled: true
    metrics:
      enabled: true
      prometheus:
        enabled: true

# Docker profile configuration
---
spring:
  config:
    activate:
      on-profile: docker
  
  cloud:
    gateway:
      routes:
        # Task Service Routes (Docker)
        - id: task-service-routes-docker
          uri: http://task-service:8081
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - name: CircuitBreaker
              args:
                name: task-service-circuit-breaker
                fallbackUri: forward:/fallback/task-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
            - StripPrefix=0
          metadata:
            response-timeout: 5000
            connect-timeout: 3000
        
        # NLP Engine Routes (Docker)
        - id: nlp-engine-routes-docker
          uri: http://nlp-engine:8082
          predicates:
            - Path=/api/v1/nlp/**
          filters:
            - name: CircuitBreaker
              args:
                name: nlp-engine-circuit-breaker
                fallbackUri: forward:/fallback/nlp-engine
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST
            - StripPrefix=1
          metadata:
            response-timeout: 10000
            connect-timeout: 5000
        
        # Speech Service Routes (Docker)
        - id: speech-service-routes-docker
          uri: http://speech-service:8083
          predicates:
            - Path=/api/v1/speech/**
          filters:
            - name: CircuitBreaker
              args:
                name: speech-service-circuit-breaker
                fallbackUri: forward:/fallback/speech-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST
            - StripPrefix=1
          metadata:
            response-timeout: 30000
            connect-timeout: 5000
        
        # Health Check Routes (Docker)
        - id: health-check-routes-docker
          uri: http://task-service:8081
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: health-check-circuit-breaker
                fallbackUri: forward:/fallback/health

  # Redis Configuration for Docker
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0