global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Task Service (Spring Boot)
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # NLP Engine
  - job_name: 'nlp-engine'
    static_configs:
      - targets: ['nlp-engine:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Speech Service
  - job_name: 'speech-service'
    static_configs:
      - targets: ['speech-service:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Gateway Service
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s 