name: AutoDev

on:
  issues:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  implement:
    if: github.event_name == 'workflow_dispatch' || (github.event.label.name == 'auto-dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install aider
        run: |
          python -m pip install -U aider-install
          aider-install

      - name: Run aider
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Implement the task described in the triggering Issue or manual dispatch." > prompt.txt
          aider --model gpt-4o --yes --message "$(cat prompt.txt)" --auto-commit

      - name: Run repository tests
        run: |
          bash ./ci/run_all_tests.sh | tee tests.out

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT || github.token }}
          branch: "autodev/${{ github.run_id }}"
          base: main
          title: "AutoDev: implementation"
          body: |
            Auto-generated by AutoDev workflow.
            See tests output in artifact or logs.
